/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.view;

import com.mycompany.model.bean.Aluno;
import com.mycompany.model.bean.Pedido;
import com.mycompany.model.dao.PedidoDAO;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author alan
 */
public class TelaConfirmacao extends javax.swing.JInternalFrame {
boolean lanche =false;
boolean almoco = false;
Aluno alu;
    /**
     * Creates new form TelaConfirmacaoi
     */
    public TelaConfirmacao() {
        initComponents();
         datas();
    }
public void recebe(Aluno aluno){
            jLmatricula.setText(aluno.getMatricula());
            jlId.setText(aluno.getId().toString());
            jLNome.setText(aluno.getNome());
            jLTurno.setText(aluno.getTurno());
            alu = aluno;
        }
    
    
     public void datas(){
                 
         
    jLhora.setBounds(10,12,70,20);
    jLhora.setBounds(10,37,60,20);
    Thread th = new Thread(new Runnable() { //cria uma thread
        public void run() {
            while(true) { //roda indefinidamente
                Date data = Calendar.getInstance().getTime();
                DateFormat d = DateFormat.getDateInstance(3);
                DateFormat h = DateFormat.getTimeInstance();
                jLdata.setText(d.format(data)   );
                jLhora.setText(h.format(data));     
                
                
                try {
                    Thread.sleep(1000); //espera 1 segundo para fazer a nova evolução
                } catch(InterruptedException ex){
                }
            }
        }
    }); th.start();
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBlanche = new javax.swing.JButton();
        jBconfirmar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLdata = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLmatricula = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLTurno = new javax.swing.JLabel();
        jLNome = new javax.swing.JLabel();
        jLresposta = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jBlanche.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jBlanche.setForeground(new java.awt.Color(0, 204, 0));
        jBlanche.setText("SOLICITAR BRINDE");
        jBlanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlancheActionPerformed(evt);
            }
        });

        jBconfirmar.setBackground(new java.awt.Color(51, 153, 0));
        jBconfirmar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBconfirmar.setForeground(new java.awt.Color(255, 255, 255));
        jBconfirmar.setText("CONFIRMAR");
        jBconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBconfirmarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel6.setText("DATA:");

        jLdata.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLdata.setText("jLabel6");

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setText("Email:");

        jLmatricula.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLmatricula.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Senha:");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setText("Nome:");

        jLTurno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLTurno.setText("jLabel4");

        jLNome.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLNome.setText("jLabel4");

        jLresposta.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLresposta.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 415, Short.MAX_VALUE)
                .addComponent(jLresposta, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(457, 457, 457))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTurno)
                    .addComponent(jLmatricula)
                    .addComponent(jLNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLdata)
                .addGap(168, 168, 168))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(528, 528, 528)
                        .addComponent(jBconfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(469, 469, 469)
                        .addComponent(jBlanche, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLdata)
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(jLmatricula))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLNome)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLTurno)
                                    .addComponent(jLabel2))))
                        .addGap(430, 430, 430))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLresposta)
                        .addGap(42, 42, 42)
                        .addComponent(jBlanche, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)))
                .addComponent(jBconfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addGap(125, 125, 125))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBlancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlancheActionPerformed
        String complemento;
        complemento = jLresposta.getText();
        jLresposta.setText("Lanche Solicitado \n" +"; \n "+ complemento);
        jBlanche.setEnabled(false);
        lanche = true;
    }//GEN-LAST:event_jBlancheActionPerformed

    private void jBconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconfirmarActionPerformed

        try{
            Pedido pedido = new Pedido();

            pedido.setAluno(alu);
            pedido.setDia(jLdata.getText());
            pedido.setHora(jLhora.getText());
            pedido.setAlmoco(almoco);
            pedido.setLanche(lanche);

            PedidoDAO pdao = new PedidoDAO();
            List<Pedido> listaa = pdao.Buscar(alu.getId(), pedido.getDia());

            if(listaa.size()<1){
                pdao.salvar(pedido);
                JOptionPane.showMessageDialog(null,jLresposta.getText() + " Confirmado" + jLhora.getText());
            }else{
                JOptionPane.showMessageDialog(null,"Pedido ja realizado NEsta data");

            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        LoginAluno log = new LoginAluno();
        getParent().add(log);
        log.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jBconfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBconfirmar;
    private javax.swing.JButton jBlanche;
    public javax.swing.JLabel jLNome;
    public javax.swing.JLabel jLTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLdata;
    public javax.swing.JLabel jLmatricula;
    private javax.swing.JLabel jLresposta;
    // End of variables declaration//GEN-END:variables
}
